forge 'https://forge.puppet.com'

mod 'puppet-puppetboard', '5.0.0'
mod 'puppet-python', '2.2.2'
mod 'puppetlabs-apache', '4.0.0'
mod 'puppetlabs-concat', '5.2.0'
mod 'puppetlabs-firewall', '1.15.1'
mod 'puppetlabs-inifile', '2.5.0'
mod 'puppetlabs-postgresql', '5.12.0'
mod 'puppetlabs-puppetdb', '7.1.0'
mod 'puppetlabs-stdlib', '5.2.0'
mod 'puppetlabs-vcsrepo', '2.4.0'
